apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: platform-product
spec:
  forProvider:
    location: West Europe
    tags:
      provisioner: crossplane
---
apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: platform-vnet
spec:
  forProvider:
    addressSpace:
      - 10.0.0.0/16
    location: West Europe
    resourceGroupName: platform-product
---
apiVersion: keyvault.azure.upbound.io/v1beta1
kind: Vault
metadata:
  name: platformproductgmck
spec:
  forProvider:
    location: West Europe
    resourceGroupName: platform-product
    skuName: standard
    tenantId: 6b4cd77d-8a3a-478b-af45-27b8689a38eb
---
apiVersion: storage.azure.upbound.io/v1beta1
kind: Account
metadata:
  name: platformproductgmck
spec:
  forProvider:
    accountKind: StorageV2
    accountReplicationType: LRS
    accountTier: Standard
    isHnsEnabled: false
    location: West Europe
    resourceGroupName: platform-product